/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registroestudiantes;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public final class Visual extends javax.swing.JFrame {

    EasyList listaEstudiantes;
    int x, y;

    public void ReproducirSonido(String nombreSonido) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(nombreSonido).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            System.out.println("Error al reproducir el sonido.");
        }
    }

    public void setPage1true() {
        page1.setVisible(true);
        page1.setEnabled(true);
    }

    public void setPage1false() {
        page1.setVisible(false);
        page1.setEnabled(false);
    }

    public void setPage2true() {
        page2.setVisible(true);
        page2.setEnabled(true);
    }

    public void setPage2false() {
        page2.setVisible(false);
        page2.setEnabled(false);
    }

    public void setPage3true() {
        page3.setVisible(true);
        page3.setEnabled(true);
    }

    public void setPage3false() {
        page3.setVisible(false);
        page3.setEnabled(false);
    }
    ImageIcon icon = new ImageIcon("src/X.png");

    public void seticonx() {
        exiticon.setIcon(icon);
    }

    public void setSearchIdfalse() {
        jTfsearchId.setVisible(false);
    }

    public Visual() {
        initComponents();
        setPage2false();
        setPage3false();
        seticonx();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        setSearchIdfalse();

        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("Género");
        modeloTabla.addColumn("Nombre del Tutor");
        modeloTabla.addColumn("Teléfono del Tutor");

        listaEstudiantes = new EasyList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPage2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        setPage1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        setPage3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exiticon = new javax.swing.JLabel();
        page3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInformes = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        page1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        sLage = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTutorName = new javax.swing.JTextField();
        tfTutorPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jCaddTo = new javax.swing.JComboBox<>();
        jTfsearchId = new javax.swing.JTextField();
        page2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setPage2.setBackground(new java.awt.Color(153, 153, 153));
        setPage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage2MouseClicked(evt);
            }
        });
        setPage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Visualizacion");
        setPage2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 30));

        getContentPane().add(setPage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 140, 40));

        setPage1.setBackground(new java.awt.Color(204, 204, 204));
        setPage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage1MouseClicked(evt);
            }
        });
        setPage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Adicion");
        setPage1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 30));

        getContentPane().add(setPage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        setPage3.setBackground(new java.awt.Color(153, 153, 153));
        setPage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setPage3MouseClicked(evt);
            }
        });
        setPage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Reporte");
        setPage3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 118, 30));

        getContentPane().add(setPage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 40));

        jPanel1.setMaximumSize(new java.awt.Dimension(37, 37));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(37, 37));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exiticon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exiticon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        page3.setBackground(new java.awt.Color(204, 204, 204));
        page3.setPreferredSize(new java.awt.Dimension(565, 510));

        textAreaInformes.setColumns(20);
        textAreaInformes.setRows(5);
        jScrollPane2.setViewportView(textAreaInformes);

        btn1.setText("Informe 1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setText("Informe 3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setText("Informe 2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page3Layout = new javax.swing.GroupLayout(page3);
        page3.setLayout(page3Layout);
        page3Layout.setHorizontalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(page3Layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn2)
                        .addGap(135, 135, 135)
                        .addComponent(btn3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        page3Layout.setVerticalGroup(
            page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(page3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(page3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 510));

        page1.setBackground(new java.awt.Color(204, 204, 204));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        sLage.setMaximum(12);
        sLage.setMinimum(7);

        jLabel10.setText("Edad del Estudiante");

        jLabel11.setText("Telefono del Tutor");

        jLabel12.setText("Nombre del Tutor");

        jLabel13.setText("ID del Estudiante");

        jLabel14.setText("Nombre del Estudiante");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel15.setText("Género del Estudiante");

        jCaddTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar al final", "Agregar al Inicio", "Agregar despues de:" }));
        jCaddTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCaddToMouseExited(evt);
            }
        });
        jCaddTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaddToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout page1Layout = new javax.swing.GroupLayout(page1);
        page1.setLayout(page1Layout);
        page1Layout.setHorizontalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page1Layout.createSequentialGroup()
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(page1Layout.createSequentialGroup()
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(page1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(page1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGender, javax.swing.GroupLayout.Alignment.TRAILING, 0, 168, Short.MAX_VALUE)
                            .addComponent(tfName)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfTutorPhone)
                            .addComponent(tfTutorName)
                            .addComponent(sLage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(page1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCaddTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfsearchId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)))
                .addGap(23, 23, 23))
        );
        page1Layout.setVerticalGroup(
            page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTutorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTutorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(page1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jCaddTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfsearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        getContentPane().add(page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 640, 510));

        page2.setBackground(new java.awt.Color(204, 204, 204));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);

        javax.swing.GroupLayout page2Layout = new javax.swing.GroupLayout(page2);
        page2.setLayout(page2Layout);
        page2Layout.setHorizontalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        page2Layout.setVerticalGroup(
            page2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String generarInforme1() {
        StringBuilder informe = new StringBuilder();
        informe.append("Estudiantes de mayor edad en los cursos primero y quinto:\n\n");

        // Obtener los estudiantes de mayor edad en los cursos primero y quinto
        StudentNodo estudianteMayorPrimerGrado = EasyList.obtenerEstudianteMayorEdadPorGrado("Primero");
        StudentNodo estudianteMayorQuintoGrado = EasyList.obtenerEstudianteMayorEdadPorGrado("Quinto");

        // Agregar los resultados al informe
        if (estudianteMayorPrimerGrado != null) {
            informe.append("Mayor edad en primer grado: ").append(estudianteMayorPrimerGrado.name)
                    .append(", Sexo: ").append(estudianteMayorPrimerGrado.gender).append("\n");
        }
        if (estudianteMayorQuintoGrado != null) {
            informe.append("Mayor edad en quinto grado: ").append(estudianteMayorQuintoGrado.name)
                    .append(", Sexo: ").append(estudianteMayorQuintoGrado.gender).append("\n");
        }

        return informe.toString();
    }

    public String generarInforme2() {
        StringBuilder informe = new StringBuilder();
        informe.append("Mujeres en quinto grado de primaria:\n\n");

        // Obtener las mujeres en quinto grado de primaria
        List<StudentNodo> mujeresQuintoGrado = EasyList.obtenerEstudiantesPorGradoYGenero("Quinto", "Femenino");
        int cantidadMujeres = mujeresQuintoGrado.size();

        // Calcular la edad promedio de las mujeres en quinto grado de primaria
        double edadPromedio = 0;
        for (StudentNodo estudiante : mujeresQuintoGrado) {
            edadPromedio += estudiante.age;
        }
        if (cantidadMujeres > 0) {
            edadPromedio /= cantidadMujeres;
        }

        // Agregar los resultados al informe
        informe.append("Cantidad de mujeres: ").append(cantidadMujeres).append("\n");
        informe.append("Edad promedio: ").append(edadPromedio).append("\n");
        informe.append("Nombres de las mujeres:\n");
        for (StudentNodo estudiante : mujeresQuintoGrado) {
            informe.append("- ").append(estudiante.name).append("\n");
        }

        return informe.toString();
    }

    public String generarInforme3() {
        StringBuilder informe = new StringBuilder();
        informe.append("Ingreso al primer grado:\n\n");

        // Obtener el ingreso al primer grado por género
        int cantidadMujeresPrimerGrado = EasyList.obtenerCantidadEstudiantesPorGradoYGenero("Primero", "Femenino");
        int cantidadHombresPrimerGrado = EasyList.obtenerCantidadEstudiantesPorGradoYGenero("Primero", "Masculino");

        // Agregar los resultados al informe
        informe.append("Cantidad de mujeres: ").append(cantidadMujeresPrimerGrado).append("\n");
        informe.append("Cantidad de hombres: ").append(cantidadHombresPrimerGrado).append("\n");

        return informe.toString();
    }

// Method to add student to the list
    public void addStudentToEasyList(
            JTextField tfId,
            JTextField tfName,
            JTextField tfTutorName,
            JTextField tfTutorPhone,
            JComboBox cbGender,
            JSlider sLage) {
        listaEstudiantes.addToEnd(tfId, tfName, tfTutorName, tfTutorPhone, cbGender, sLage);
    }

    // Method to fill JTable with student data
    public void fillJTable(JTable tab) {
        listaEstudiantes.fillJTable(tab);
    }

    public void modifyStudentData(
            String tfId,
            String tfName,
            String tfTutorName,
            String tfTutorPhone,
            String cbGender,
            int sLage) {
        listaEstudiantes.modifyData(tfId, tfName, tfTutorName, tfTutorPhone, cbGender, sLage);
    }

    public void deleteStudent(String id) {
        listaEstudiantes.delStudent(id);
    }

    private void setPage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage2MouseClicked
        if (page2.isVisible() == true && page2.isEnabled() == true) {
            ReproducirSonido("src/Error.wav");
        } else {
            setPage1false();
            setPage3false();
            setPage2true();
            setPage2.setBackground(new Color(204, 204, 204));
            setPage1.setBackground(new Color(153, 153, 153));
            setPage3.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_setPage2MouseClicked

    private void setPage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage1MouseClicked
        if (page1.isVisible() == true && page1.isEnabled() == true) {
            ReproducirSonido("src/Error.wav");
        } else {
            setPage2false();
            setPage3false();
            setPage1true();
            setPage1.setBackground(new Color(204, 204, 204));
            setPage2.setBackground(new Color(153, 153, 153));
            setPage3.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_setPage1MouseClicked

    private void setPage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setPage3MouseClicked
        if (page3.isVisible() == true && page3.isEnabled() == true) {
            ReproducirSonido("src/Error.wav");
        } else {
            setPage1false();
            setPage2false();
            setPage3true();
            setPage3.setBackground(new Color(204, 204, 204));
            setPage1.setBackground(new Color(153, 153, 153));
            setPage2.setBackground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_setPage3MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Obtener los datos del estudiante desde los campos de texto y otros componentes
        switch (jCaddTo.getSelectedIndex()) {
            case 0:
                listaEstudiantes.addToEnd(tfId, tfName, tfTutorName, tfTutorPhone, cbGender, sLage, sLgrade);
            case 1:
                listaEstudiantes.addToStart(tfId, tfName, tfTutorName, tfTutorPhone, cbGender, sLage, sLgrade);
            case 2:
                listaEstudiantes.addNextTo(tfId, tfName, tfTutorName, tfTutorPhone, cbGender, sLage, jTfsearchId.getText(), sLgrade);
        }

        tfId.setText("");
        tfName.setText("");
        tfTutorName.setText("");
        tfTutorPhone.setText("");
        cbGender.setSelectedIndex(0);
        sLage.setValue(18);

        JOptionPane.showMessageDialog(null, "Estudiante agregado exitosamente");
        listaEstudiantes.fillJTable(tab);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        generarInforme1();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        generarInforme2();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        generarInforme3();
    }//GEN-LAST:event_btn3ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_formMouseDragged

    private void jCaddToMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCaddToMouseExited

    }//GEN-LAST:event_jCaddToMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void jCaddToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaddToActionPerformed

            jTfsearchId.setVisible((jCaddTo.getSelectedIndex() == 2));    
    }//GEN-LAST:event_jCaddToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JLabel exiticon;
    private javax.swing.JComboBox<String> jCaddTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTfsearchId;
    private javax.swing.JPanel page1;
    private javax.swing.JPanel page2;
    private javax.swing.JPanel page3;
    private javax.swing.JSlider sLage;
    private javax.swing.JPanel setPage1;
    private javax.swing.JPanel setPage2;
    private javax.swing.JPanel setPage3;
    private javax.swing.JTable tab;
    private javax.swing.JTextArea textAreaInformes;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfTutorName;
    private javax.swing.JTextField tfTutorPhone;
    // End of variables declaration//GEN-END:variables
}
